/**
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Problem model module.
 * @module model/Problem
 * @version 1.0.0
 */
class Problem {
    /**
     * Constructs a new <code>Problem</code>.
     * A Problem Details object (RFC 7807)
     * @alias module:model/Problem
     */
    constructor() { 
        
        Problem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Problem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Problem} obj Optional instance to populate.
     * @return {module:model/Problem} The populated <code>Problem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Problem();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'Number');
            }
            if (data.hasOwnProperty('detail')) {
                obj['detail'] = ApiClient.convertToType(data['detail'], 'String');
            }
            if (data.hasOwnProperty('instance')) {
                obj['instance'] = ApiClient.convertToType(data['instance'], 'String');
            }
        }
        return obj;
    }


}

/**
 * A relative URI reference that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g. using HTML).
 * @member {String} type
 * @default 'about:blank'
 */
Problem.prototype['type'] = 'about:blank';

/**
 * A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized)
 * @member {String} title
 */
Problem.prototype['title'] = undefined;

/**
 * The HTTP status code generated by the origin server for this occurrence of the problem.
 * @member {Number} status
 */
Problem.prototype['status'] = undefined;

/**
 * A human-readable explanation specific to this occurrence of the problem
 * @member {String} detail
 */
Problem.prototype['detail'] = undefined;

/**
 * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
 * @member {String} instance
 */
Problem.prototype['instance'] = undefined;






export default Problem;

