/**
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AdditionalFeatures from './AdditionalFeatures';
import RequiredFeatures from './RequiredFeatures';

/**
 * The PropertyFeatures model module.
 * @module model/PropertyFeatures
 * @version 1.0.0
 */
class PropertyFeatures {
    /**
     * Constructs a new <code>PropertyFeatures</code>.
     * @alias module:model/PropertyFeatures
     * @param requiredFeatures {module:model/RequiredFeatures} 
     */
    constructor(requiredFeatures) { 
        
        PropertyFeatures.initialize(this, requiredFeatures);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, requiredFeatures) { 
        obj['requiredFeatures'] = requiredFeatures;
    }

    /**
     * Constructs a <code>PropertyFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PropertyFeatures} obj Optional instance to populate.
     * @return {module:model/PropertyFeatures} The populated <code>PropertyFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PropertyFeatures();

            if (data.hasOwnProperty('requiredFeatures')) {
                obj['requiredFeatures'] = RequiredFeatures.constructFromObject(data['requiredFeatures']);
            }
            if (data.hasOwnProperty('additionalFeatures')) {
                obj['additionalFeatures'] = AdditionalFeatures.constructFromObject(data['additionalFeatures']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/RequiredFeatures} requiredFeatures
 */
PropertyFeatures.prototype['requiredFeatures'] = undefined;

/**
 * @member {module:model/AdditionalFeatures} additionalFeatures
 */
PropertyFeatures.prototype['additionalFeatures'] = undefined;






export default PropertyFeatures;

