/**
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FloorLevel from './FloorLevel';
import NewOrResale from './NewOrResale';
import PropertyType from './PropertyType';

/**
 * The RequiredFeatures model module.
 * @module model/RequiredFeatures
 * @version 1.0.0
 */
class RequiredFeatures {
    /**
     * Constructs a new <code>RequiredFeatures</code>.
     * @alias module:model/RequiredFeatures
     * @param postcode {String} Postcode
     * @param newOrResale {module:model/NewOrResale} 
     * @param floorLevel {module:model/FloorLevel} 
     * @param totalFloorAreaInSqf {Number} Floor area (sqf)
     * @param propertyType {module:model/PropertyType} 
     * @param numberOfRooms {Number} 
     */
    constructor(postcode, newOrResale, floorLevel, totalFloorAreaInSqf, propertyType, numberOfRooms) { 
        
        RequiredFeatures.initialize(this, postcode, newOrResale, floorLevel, totalFloorAreaInSqf, propertyType, numberOfRooms);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, postcode, newOrResale, floorLevel, totalFloorAreaInSqf, propertyType, numberOfRooms) { 
        obj['postcode'] = postcode;
        obj['newOrResale'] = newOrResale;
        obj['floorLevel'] = floorLevel;
        obj['totalFloorAreaInSqf'] = totalFloorAreaInSqf;
        obj['propertyType'] = propertyType;
        obj['numberOfRooms'] = numberOfRooms;
    }

    /**
     * Constructs a <code>RequiredFeatures</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RequiredFeatures} obj Optional instance to populate.
     * @return {module:model/RequiredFeatures} The populated <code>RequiredFeatures</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RequiredFeatures();

            if (data.hasOwnProperty('postcode')) {
                obj['postcode'] = ApiClient.convertToType(data['postcode'], 'String');
            }
            if (data.hasOwnProperty('newOrResale')) {
                obj['newOrResale'] = NewOrResale.constructFromObject(data['newOrResale']);
            }
            if (data.hasOwnProperty('floorLevel')) {
                obj['floorLevel'] = FloorLevel.constructFromObject(data['floorLevel']);
            }
            if (data.hasOwnProperty('totalFloorAreaInSqf')) {
                obj['totalFloorAreaInSqf'] = ApiClient.convertToType(data['totalFloorAreaInSqf'], 'Number');
            }
            if (data.hasOwnProperty('propertyType')) {
                obj['propertyType'] = PropertyType.constructFromObject(data['propertyType']);
            }
            if (data.hasOwnProperty('numberOfRooms')) {
                obj['numberOfRooms'] = ApiClient.convertToType(data['numberOfRooms'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * Postcode
 * @member {String} postcode
 */
RequiredFeatures.prototype['postcode'] = undefined;

/**
 * @member {module:model/NewOrResale} newOrResale
 */
RequiredFeatures.prototype['newOrResale'] = undefined;

/**
 * @member {module:model/FloorLevel} floorLevel
 */
RequiredFeatures.prototype['floorLevel'] = undefined;

/**
 * Floor area (sqf)
 * @member {Number} totalFloorAreaInSqf
 */
RequiredFeatures.prototype['totalFloorAreaInSqf'] = undefined;

/**
 * @member {module:model/PropertyType} propertyType
 */
RequiredFeatures.prototype['propertyType'] = undefined;

/**
 * @member {Number} numberOfRooms
 */
RequiredFeatures.prototype['numberOfRooms'] = undefined;






export default RequiredFeatures;

