/**
 * AVM
 * This is api for AVM (automated valuation machine)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@enbisys.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ValuationPriceDistribution model module.
 * @module model/ValuationPriceDistribution
 * @version 1.0.0
 */
class ValuationPriceDistribution {
    /**
     * Constructs a new <code>ValuationPriceDistribution</code>.
     * @alias module:model/ValuationPriceDistribution
     */
    constructor() { 
        
        ValuationPriceDistribution.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ValuationPriceDistribution</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ValuationPriceDistribution} obj Optional instance to populate.
     * @return {module:model/ValuationPriceDistribution} The populated <code>ValuationPriceDistribution</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ValuationPriceDistribution();

            if (data.hasOwnProperty('priceFrom')) {
                obj['priceFrom'] = ApiClient.convertToType(data['priceFrom'], 'Number');
            }
            if (data.hasOwnProperty('priceTo')) {
                obj['priceTo'] = ApiClient.convertToType(data['priceTo'], 'Number');
            }
            if (data.hasOwnProperty('probability')) {
                obj['probability'] = ApiClient.convertToType(data['probability'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * left subrange boundary
 * @member {Number} priceFrom
 */
ValuationPriceDistribution.prototype['priceFrom'] = undefined;

/**
 * right subrange boundary
 * @member {Number} priceTo
 */
ValuationPriceDistribution.prototype['priceTo'] = undefined;

/**
 * Probability that price is within the specified boundaries
 * @member {Number} probability
 */
ValuationPriceDistribution.prototype['probability'] = undefined;






export default ValuationPriceDistribution;

